apiVersion: v1
kind: Pod
metadata:
  name: te-agent-pod
  labels:
    app: te-agent-pod
spec:
  hostname: te-agent-pod
  containers:
  - name: te-agent-pod
    image: thousandeyes/enterprise-agent:latest
    imagePullPolicy: Always
    command: ["/sbin/my_init"]
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - SYS_ADMIN
    env:
      - name: TEAGENT_ACCOUNT_TOKEN
        valueFrom:
          secretKeyRef:
            name: te-credentials
            key: ACCOUNT_TOKEN
      - name: TEAGENT_INET
        value: "4"
      - name: KUBERNETES
        value: "true"
      - name: TEST
        value: "true"
      - name: AGENT_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
    resources:
      requests:
        memory: "1Gi"
        cpu: "100m"
      limits:
        memory: "2Gi"
        cpu: "200m"
    tty: true
    volumeMounts:
      - name: vol-agent
        mountPath: /var/lib/te-agent
        subPathExpr: $(AGENT_NAME)/te-agent
      - name: vol-agent
        mountPath: /var/lib/te-browserbot
        subPathExpr: $(AGENT_NAME)/te-browserbot
      - name: vol-agent
        mountPath: /var/log/agent
        subPathExpr: $(AGENT_NAME)/log
  volumes:
    - name: vol-agent
      persistentVolumeClaim:
        claimName: te-pvc
  terminationGracePeriodSeconds: 10
  restartPolicy: Always
  # nodeSelector:
  #   host: host1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: te-pv
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    # This disk must be created manually
    pdName: te-pv-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: te-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: te-pv