# apiVersion: v1
# kind: Service
# metadata:
#   name: te-agent-statefulset
#   labels:
#     app: te-agent-statefulset
# spec:
#   ports:
#   - port: 80
#     name: web
#   - port: 443
#     name: https
#   clusterIP: None
#   selector:
#     app: te-agent-statefulset
# ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: te-agent-statefulset
spec:
  selector:
    matchLabels:
      app: te-agent-statefulset
  replicas: 1
  serviceName: "te-agent-statefulset"
  template:
    metadata:
      labels:
        app: te-agent-statefulset
    spec:
      containers:
      - name: te-agent-statefulset
        image: thousandeyes/enterprise-agent:latest
        command: ["/sbin/my_init"]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
        env:
          - name: TEAGENT_ACCOUNT_TOKEN
            valueFrom:
              secretKeyRef:
                name: te-credentials
                key: ACCOUNT_TOKEN
          - name: TEAGENT_INET
            value: "4"
          - name: KUBERNETES
            value: "true"
          - name: AGENT_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                # StatefulSet metadata.name will be te-agent-boutique-0
                fieldPath: metadata.name
        resources:
          requests:
            memory: "1Gi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "200m"
        tty: true
        # subPathExpr: $(AGENT_NAME)/ creates a separate folder
        # for each agent on persistant volume, ensuring there is 
        # no conflict if multiple agents deployed
        volumeMounts:
          - name: vol-agent-statefulset
            mountPath: /var/lib/te-agent
            subPathExpr: $(AGENT_NAME)/te-agent
          - name: vol-agent-statefulset
            mountPath: /var/lib/te-browserbot
            subPathExpr: $(AGENT_NAME)/te-browserbot
          - name: vol-agent-statefulset
            mountPath: /var/log/agent
            subPathExpr: $(AGENT_NAME)/log
      nodeSelector:
        teagent: te-agent-boutique
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: vol-agent-statefulset
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
